version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
    ignore:
      - dependency-name: "chalk"
        versions: ["5.0.0"]
